version: '3'
services:
  pgsql:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - rest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  php:
    build:
      context: .
      dockerfile: ./conf/dockerfile
    links:
      - pgsql
    networks:
      - rest
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    links:
      - php
    ports:
      - 8050:8050
    networks:
      - rest
  adminer:
    image: adminer
    networks:
      - rest
    ports:
      - 8080:8080
networks:
  rest:
    driver: bridge
